import { Recipe, Category, UserProfile } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'mon-nuoc',
    name: 'Món Nước & Súp',
    description: 'Những món nước đậm đà tinh túy, nước dùng ngọt thanh ninh từ xương và thảo mộc thơm lừng.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    recipeCount: 18,
    iconName: 'Soup',
    featured: true,
  },
  {
    id: 'cat-2',
    slug: 'mon-xao-kho',
    name: 'Món Mặn & Kho Xào',
    description: 'Hương vị mặn mà đưa cơm cho bữa cơm gia đình truyền thống chuẩn vị Việt.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    recipeCount: 24,
    iconName: 'Flame',
    featured: true,
  },
  {
    id: 'cat-3',
    slug: 'an-kieng-healthy',
    name: 'Eat Clean & Ăn Kiêng',
    description: 'Chế độ dinh dưỡng cân bằng, ít calo, giàu protein và chất xơ tươi ngon tốt cho sức khỏe.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    recipeCount: 15,
    iconName: 'Salad',
    featured: true,
  },
  {
    id: 'cat-4',
    slug: 'banh-va-trang-mieng',
    name: 'Bánh & Tráng Miệng',
    description: 'Thế giới đồ ngọt ngọt ngào, bánh nướng giòn rụm và các món chè thanh mát giải nhiệt.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    recipeCount: 12,
    iconName: 'Cake',
    featured: true,
  },
  {
    id: 'cat-5',
    slug: 'mon-chay',
    name: 'Món Chay Thanh Tịnh',
    description: 'Ẩm thực thuần chay từ nấm, rau củ hữu cơ mang lại sự nhẹ nhàng và thanh tịnh cho tâm hồn.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    recipeCount: 9,
    iconName: 'Leaf',
    featured: false,
  },
  {
    id: 'cat-6',
    slug: 'thuc-uong',
    name: 'Trà & Thức Uống',
    description: 'Các loại trà trái cây nhiệt đới, cà phê rang xay và sinh tố giải nhiệt bổ dưỡng.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    recipeCount: 8,
    iconName: 'Coffee',
    featured: false,
  },
];

export const MOCK_AUTHORS = [
  {
    id: 'user-1',
    name: 'Lê Anh Khoa',
    email: 'anhkhoa@culinaryblog.dlu.vn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    role: 'admin' as const,
    bio: 'Blogger ẩm thực và sinh viên năm 3 ĐH Đà Lạt. Đam mê gìn giữ hương vị ẩm thực ba miền và khám phá nghệ thuật ẩm thực thế giới.',
  },
  {
    id: 'user-2',
    name: 'Bếp Trưởng Mai Hương',
    email: 'maihuong.chef@culinary.vn',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    role: 'author' as const,
    bio: 'Đầu bếp món Việt với hơn 8 năm nghiên cứu gia vị thảo mộc và chế độ ăn healthy lành mạnh.',
  },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'rec-1',
    slug: 'pho-bo-ha-noi-truyen-thong',
    title: 'Phở Bò Hà Nội Truyền Thống Nước Dùng Thanh Trong',
    description: 'Bí quyết nấu nồi phở bò Hà Nội gia truyền với nước dùng trong vắt, ngọt tự nhiên từ xương bò hầm 8 tiếng cùng quế, hồi, thảo quả nướng thơm phức.',
    coverImage: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'mon-nuoc',
    categoryName: 'Món Nước & Súp',
    author: MOCK_AUTHORS[0],
    difficulty: 'Khó',
    prepTimeMinutes: 45,
    cookTimeMinutes: 360,
    servings: 6,
    calories: 485,
    rating: 4.9,
    reviewCount: 142,
    tags: ['Phở Bò', 'Món Hà Nội', 'Món Nước', 'Truyền Thống'],
    isFeatured: true,
    status: 'published',
    createdAt: '2025-02-15T08:00:00Z',
    updatedAt: '2025-02-18T10:30:00Z',
    nutrition: {
      calories: 485,
      protein: 34,
      carbohydrates: 62,
      fat: 11,
      fiber: 3,
      sodium: 980,
    },
    ingredients: [
      { id: 'i1', name: 'Xương ống và đuôi bò', amount: '2', unit: 'kg', notes: 'Rửa sạch bằng muối và chần nước sôi' },
      { id: 'i2', name: 'Thịt bắp bò hoa & nạm bò', amount: '800', unit: 'g', notes: 'Thịt tươi để thái tái hoặc luộc chín' },
      { id: 'i3', name: 'Bánh phở tươi sợi nhỏ', amount: '1', unit: 'kg', notes: 'Trần nóng trước khi chan nước dùng' },
      { id: 'i4', name: 'Gừng ta & hành khô tím', amount: '200', unit: 'g', notes: 'Nướng cháy xém cạnh rồi cạo vỏ' },
      { id: 'i5', name: 'Hoa hồi, thảo quả, quế thanh, hạt mùi', amount: '1', unit: 'gói nhỏ', notes: 'Rang thơm cho vào túi lọc' },
      { id: 'i6', name: 'Hành hoa, rau mùi ta, chanh, ớt tươi', amount: '150', unit: 'g' },
      { id: 'i7', name: 'Nước mắm cốt truyền thống & muối hột', amount: '3', unit: 'thìa canh' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Sơ chế và làm sạch xương bò',
        description: 'Ngâm xương bò trong nước muối loãng 1 tiếng. Cho vào nồi đun sôi bùng 5 phút cùng gừng đập dập để loại bỏ hoàn toàn bọt bẩn và mùi gây. Rửa lại thật sạch dưới vòi nước lạnh.',
        durationMinutes: 30,
        tip: 'Khâu chần xương là bí quyết vàng để nước dùng phở trong veo không bị đục.',
      },
      {
        step: 2,
        title: 'Nướng hành gừng và rang gia vị thảo mộc',
        description: 'Nướng hành tím và gừng trên than hoa hoặc bếp ga cho đến khi dậy mùi thơm và hơi xém vỏ. Rửa sạch muội than. Rang thơm hoa hồi, thảo quả, quế và hạt mùi trên chảo lửa nhỏ rồi bọc vào túi vải sạch.',
        durationMinutes: 15,
      },
      {
        step: 3,
        title: 'Ninh nước dùng phở',
        description: 'Cho xương bò, nạm bò vào nồi cùng 5 lít nước lạnh. Đun sôi rồi hạ lửa riu riu, mở hé vung và liên tục hớt bọt. Sau 2 giờ, vớt phần nạm bò ra ngâm nước đá rồi thái lát mỏng. Thả túi thảo mộc và hành gừng nướng vào ninh tiếp 4 - 6 tiếng.',
        durationMinutes: 300,
        tip: 'Chỉ nêm muối hột và nước mắm cốt ngon ở 30 phút cuối để nước phở không bị chua.',
      },
      {
        step: 4,
        title: 'Hoàn thiện tô phở',
        description: 'Trần bánh phở qua nước sôi, xếp vào bát. Bày thịt bò tái thái mỏng, nạm chín, rắc nhiều đầu hành chẻ và hành hoa thái nhỏ. Chan nước dùng sôi sùng sục ngập bánh phở. Dùng kèm tương ớt phố cổ và giấm tỏi.',
        durationMinutes: 10,
      },
    ],
  },
  {
    id: 'rec-2',
    slug: 'bun-bo-hue-chuan-vi-co-do',
    title: 'Bún Bò Huế Chuẩn Vị Cố Đô Đậm Đà Ruốc Sả',
    description: 'Món bún trứ danh miền Trung với vị cay nồng của ớt sa tế, hương thơm nồng nàn của mắm ruốc Huế và sả cây hòa quyện cùng chân giò béo ngậy.',
    coverImage: 'https://images.unsplash.com/photo-1594998893017-36147cbcae05?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'mon-nuoc',
    categoryName: 'Món Nước & Súp',
    author: MOCK_AUTHORS[1],
    difficulty: 'Trung bình',
    prepTimeMinutes: 40,
    cookTimeMinutes: 180,
    servings: 5,
    calories: 520,
    rating: 4.8,
    reviewCount: 96,
    tags: ['Bún Bò Huế', 'Miền Trung', 'Đậm Đà', 'Món Nước'],
    isFeatured: true,
    status: 'published',
    createdAt: '2025-02-12T09:00:00Z',
    updatedAt: '2025-02-14T11:00:00Z',
    nutrition: {
      calories: 520,
      protein: 36,
      carbohydrates: 55,
      fat: 16,
      fiber: 4,
      sodium: 1150,
    },
    ingredients: [
      { id: 'i21', name: 'Bắp bò & móng giò heo', amount: '1.2', unit: 'kg' },
      { id: 'i22', name: 'Mắm ruốc Huế nguyên chất', amount: '3', unit: 'thìa canh' },
      { id: 'i23', name: 'Sả cây tươi', amount: '8', unit: 'cây' },
      { id: 'i24', name: 'Hạt điều màu & ớt bột sa tế', amount: '2', unit: 'thìa canh' },
      { id: 'i25', name: 'Bún sợi to', amount: '800', unit: 'g' },
      { id: 'i26', name: 'Rau thơm: hoa chuối bào, giá đỗ, rau muống chẻ', amount: '300', unit: 'g' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Xử lý mắm ruốc Huế',
        description: 'Khuấy đều mắm ruốc với 200ml nước lạnh. Đun sôi rồi để lắng cặn, chỉ lấy phần nước trong ngọt thơm phía trên.',
        durationMinutes: 15,
      },
      {
        step: 2,
        title: 'Nấu nước dùng cùng sả đập dập',
        description: 'Hầm xương ống, bắp bò và chân giò cùng các khúc sả đập dập. Vớt bọt thường xuyên. Nêm nước trong của mắm ruốc vào nồi tạo mùi hương đặc trưng.',
        durationMinutes: 120,
      },
      {
        step: 3,
        title: 'Làm dầu màu điều và sa tế cay',
        description: 'Chưng dầu màu điều phi thơm cùng tỏi băm và sả băm nhuyễn để tạo lớp váng màu cam đỏ bắt mắt cho nước bún.',
        durationMinutes: 15,
      },
    ],
  },
  {
    id: 'rec-3',
    slug: 'salad-uc-ga-ap-chao-sot-me-rang',
    title: 'Salad Ức Gà Áp Chảo Sốt Mè Rang Giòn Ngọt Eat Clean',
    description: 'Bữa trưa lành mạnh giàu đạm, ít tinh bột với ức gà mọng nước áp chảo thảo mộc kết hợp xà lách giòn mát, bơ sáp và cà chua bi hữu cơ.',
    coverImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'an-kieng-healthy',
    categoryName: 'Eat Clean & Ăn Kiêng',
    author: MOCK_AUTHORS[0],
    difficulty: 'Dễ',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 2,
    calories: 320,
    rating: 4.7,
    reviewCount: 78,
    tags: ['Eat Clean', 'Ức Gà', 'Healthy', 'Giảm Cân'],
    isFeatured: true,
    status: 'published',
    createdAt: '2025-02-10T11:00:00Z',
    updatedAt: '2025-02-10T11:00:00Z',
    nutrition: {
      calories: 320,
      protein: 38,
      carbohydrates: 12,
      fat: 14,
      fiber: 6,
      sodium: 420,
    },
    ingredients: [
      { id: 'i31', name: 'Ức gà phi lê không da', amount: '350', unit: 'g' },
      { id: 'i32', name: 'Xà lách Romaine & xà lách xoăn', amount: '200', unit: 'g' },
      { id: 'i33', name: 'Quả bơ sáp chín tới', amount: '1', unit: 'quả' },
      { id: 'i34', name: 'Cà chua bi baby', amount: '10', unit: 'quả' },
      { id: 'i35', name: 'Sốt mè rang Kewpie hữu cơ', amount: '3', unit: 'thìa canh' },
      { id: 'i36', name: 'Dầu ô liu, muối hồng và tiêu đen giã dập', amount: '1', unit: 'ít' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Ướp ức gà',
        description: 'Dùng dao khía nhẹ vài đường trên ức gà. Ướp cùng 1 thìa cà phê dầu ô liu, muối hồng, tiêu đen và lá hương thảo trong 10 phút.',
        durationMinutes: 10,
      },
      {
        step: 2,
        title: 'Áp chảo ức gà mọng nước',
        description: 'Làm nóng chảo chống dính. Áp chảo ức gà mỗi mặt 5 - 6 phút ở lửa vừa đến khi vàng ruộm và chín đều bên trong.',
        durationMinutes: 12,
      },
      {
        step: 3,
        title: 'Trộn salad và thưởng thức',
        description: 'Thái lát ức gà, xếp lên đĩa rau xà lách, bơ sáp và cà chua bi. Rưới sốt mè rang béo bùi và thưởng thức ngay.',
        durationMinutes: 5,
      },
    ],
  },
  {
    id: 'rec-4',
    slug: 'thit-kho-tau-trung-cut-nuoc-dua',
    title: 'Thịt Ba Chỉ Kho Tàu Trứng Cút Nước Dừa Xiêm',
    description: 'Hương vị Tết cổ truyền quen thuộc với thịt ba chỉ mềm tan trong miệng ngấm đượm nước dừa bến tre ngả màu cánh gián hấp dẫn.',
    coverImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'mon-xao-kho',
    categoryName: 'Món Mặn & Kho Xào',
    author: MOCK_AUTHORS[1],
    difficulty: 'Trung bình',
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    servings: 4,
    calories: 610,
    rating: 4.9,
    reviewCount: 110,
    tags: ['Thịt Kho Tàu', 'Bữa Cơm Gia Đình', 'Món Kho', 'Món Tết'],
    isFeatured: false,
    status: 'published',
    createdAt: '2025-02-05T14:00:00Z',
    updatedAt: '2025-02-06T09:00:00Z',
    nutrition: {
      calories: 610,
      protein: 28,
      carbohydrates: 15,
      fat: 48,
      fiber: 1,
      sodium: 890,
    },
    ingredients: [
      { id: 'i41', name: 'Thịt ba chỉ rút sườn', amount: '600', unit: 'g' },
      { id: 'i42', name: 'Trứng cút (hoặc trứng gà)', amount: '16', unit: 'quả' },
      { id: 'i43', name: 'Nước dừa tươi', amount: '500', unit: 'ml' },
      { id: 'i44', name: 'Nước mắm ngon, đường phèn, tỏi, hành tím', amount: 'vừa đủ', unit: 'gia vị' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Sơ chế thịt và luộc trứng',
        description: 'Thịt rửa sạch, cắt miếng vuông quân cờ cỡ 4cm. Luộc chín trứng cút và bóc sạch vỏ.',
        durationMinutes: 15,
      },
      {
        step: 2,
        title: 'Thắng nước màu và ướp thịt',
        description: 'Thắng đường phèn thành màu caramen cánh gián. Ướp thịt cùng hành tím băm, tỏi băm và 3 thìa nước mắm trong 30 phút.',
        durationMinutes: 30,
      },
      {
        step: 3,
        title: 'Kho thịt cùng nước dừa',
        description: 'Đảo săn thịt rồi đổ ngập nước dừa tươi. Đun sôi hạ lửa liu riu trong 45 phút, thả trứng cút vào kho đến khi nước sánh lại.',
        durationMinutes: 50,
      },
    ],
  },
  {
    id: 'rec-5',
    slug: 'banh-crepe-ngan-lop-matcha-nhat-ban',
    title: 'Bánh Crepe Ngàn Lớp Matcha Nhật Bản Mát Lạnh',
    description: 'Từng lớp bánh crepe mỏng mềm đượm bột trà xanh Uji Kyoto xen kẽ lớp kem tươi béo ngậy tan chảy trên đầu lưỡi.',
    coverImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'banh-va-trang-mieng',
    categoryName: 'Bánh & Tráng Miệng',
    author: MOCK_AUTHORS[0],
    difficulty: 'Khó',
    prepTimeMinutes: 60,
    cookTimeMinutes: 40,
    servings: 8,
    calories: 380,
    rating: 4.9,
    reviewCount: 65,
    tags: ['Bánh Crepe', 'Matcha', 'Tráng Miệng', 'Bánh Lạnh'],
    isFeatured: false,
    status: 'published',
    createdAt: '2025-02-01T15:00:00Z',
    updatedAt: '2025-02-01T15:00:00Z',
    nutrition: {
      calories: 380,
      protein: 6,
      carbohydrates: 42,
      fat: 22,
      fiber: 2,
      sodium: 180,
    },
    ingredients: [
      { id: 'i51', name: 'Bột mì đa dụng & bột matcha Uji', amount: '220', unit: 'g' },
      { id: 'i52', name: 'Sữa tươi không đường', amount: '500', unit: 'ml' },
      { id: 'i53', name: 'Whipping cream & mascarpone', amount: '450', unit: 'ml' },
      { id: 'i54', name: 'Trứng gà tươi & bơ lạt đun chảy', amount: '4', unit: 'quả' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Trộn và ủ bột bánh',
        description: 'Rây mịn bột mì và bột matcha. Đánh đều cùng trứng, đường và sữa tươi. Lọc qua rây 2 lần cho thật mịn rồi để tủ lạnh 30 phút.',
        durationMinutes: 40,
      },
      {
        step: 2,
        title: 'Tráng từng lớp crepe mỏng',
        description: 'Dùng chảo chống dính nhỏ, phết bơ lạt. Đổ một muôi bột mỏng quay đều, rán mỗi mặt 1 phút rồi xếp ra để nguội.',
        durationMinutes: 40,
      },
      {
        step: 3,
        title: 'Xếp lớp bánh cùng kem tươi',
        description: 'Đánh bông whipping cream. Đặt 1 lớp bánh crepe, phết kem đều rồi đặt tiếp lớp bánh khác lặp lại 20 lần. Để tủ lạnh 3 tiếng trước khi cắt.',
        durationMinutes: 30,
      },
    ],
  },
  {
    id: 'rec-6',
    slug: 'nam-kho-tieu-chay-dua-com',
    title: 'Nấm Đùi Gà Kho Tiêu Chay Đậm Đà Đưa Cơm',
    description: 'Món chay giản dị nhưng quyến rũ bất ngờ với nấm đùi gà dai giòn sần sật quyện sốt tiêu đen cay nồng thơm lừng.',
    coverImage: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    categorySlug: 'mon-chay',
    categoryName: 'Món Chay Thanh Tịnh',
    author: MOCK_AUTHORS[1],
    difficulty: 'Dễ',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    calories: 190,
    rating: 4.6,
    reviewCount: 42,
    tags: ['Món Chay', 'Nấm Đùi Gà', 'Thanh Đạm', 'Kho Tiêu'],
    isFeatured: false,
    status: 'published',
    createdAt: '2025-01-28T09:30:00Z',
    updatedAt: '2025-01-28T09:30:00Z',
    nutrition: {
      calories: 190,
      protein: 8,
      carbohydrates: 22,
      fat: 6,
      fiber: 5,
      sodium: 620,
    },
    ingredients: [
      { id: 'i61', name: 'Nấm đùi gà tươi', amount: '400', unit: 'g' },
      { id: 'i62', name: 'Tiêu xanh & tiêu đen giã dập', amount: '2', unit: 'nhánh' },
      { id: 'i63', name: 'Nước tương đậu nành & dầu hào chay', amount: '3', unit: 'thìa canh' },
      { id: 'i64', name: 'Hành boaro (tỏi tây) phi thơm', amount: '1', unit: 'cây' },
    ],
    instructions: [
      {
        step: 1,
        title: 'Sơ chế nấm đùi gà',
        description: 'Cắt bỏ chân nấm, ngâm nước muối loãng rồi rửa sạch. Cắt khúc vừa ăn và khía nhẹ hình vảy cá để ngấm gia vị.',
        durationMinutes: 10,
      },
      {
        step: 2,
        title: 'Kho nấm với tiêu đen',
        description: 'Phi thơm boaro, cho nấm vào đảo xém cạnh. Đổ sốt nước tương, tiêu đen và rim lửa nhỏ đến khi nước sốt sệt bám quanh từng miếng nấm.',
        durationMinutes: 20,
      },
    ],
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'user-1',
  name: 'Lê Anh Khoa',
  userName: 'khoale0802',
  email: 'anhkhoa080205@gmail.com',
  emailConfirmed: true,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  role: 'admin',
  bio: 'Sinh viên năm 3 Đại học Đà Lạt (DLU) - Chuyên ngành Công nghệ Phần mềm. Đam mê ẩm thực Việt Nam, nhiếp ảnh món ăn và kiến trúc Frontend hiện đại.',
  location: 'Thành phố Đà Lạt, Lâm Đồng, Việt Nam',
  website: 'https://github.com/khoale-dlu',
  savedRecipeIds: ['rec-1', 'rec-3', 'rec-5'],
  publishedCount: 14,
  joinedDate: 'Tháng 9, 2023',
};

export const MOCK_DASHBOARD_STATS = {
  totalRecipes: 34,
  publishedRecipes: 28,
  draftRecipes: 6,
  totalViews: '184.2K',
  totalLikes: '12.8K',
  totalComments: '3,450',
  monthlyGrowth: '+24.5%',
  popularCategories: [
    { name: 'Món Nước & Súp', percentage: 42 },
    { name: 'Eat Clean & Ăn Kiêng', percentage: 28 },
    { name: 'Món Mặn & Kho Xào', percentage: 18 },
    { name: 'Bánh & Tráng Miệng', percentage: 12 },
  ],
};
